<div class="row flexListTable">
    <?php $this->layout('admin/menu'); ?>
    <div class="col-10 admin-panel-wrap light-gray-wrap">
        <?php $this->layout('admin/breadcrumbs'); ?>

        <div class="container-fluid admin-panel-content">
            <div class="wrapListTable">
                <h1 class="admin-panel__title">Freelancer list</h1>
                <hr>
                <table class="table listTable">
                    <tr>
                        <thead class="thead-default">
                        <th>ID</th>
                        <th>userID</th>
                        <th>connect_used</th>
                        <th>rate</th>
                        <th>rating</th>
                        <th>jobCount</th>
                        <th>planID</th>
                        <th>status</th>
                        </thead>
                    </tr>
                    <tbody>
                    <?php
                    foreach ($this->freelancersList as $i) {
                        if (count($this->freelancersList) == 0) {
                            echo '<p>Sorry, we don\'t have any freelancers</p>';
                        } else { ?>
                            <tr>
                                <td><?= $i->getId() ?></td>
                                <td><?= $i->getRate() ?></td>
                                <td><?= $i->getPlan() ?></td>
                                <td><?= $i->getUser()->getId() ?></td>
                                <td><?= $i->getCategoryId() ?></td>
                            </tr>

                        <?php }
                    }
                    ?>
                    </tbody>
                </table>
            </div>

            <?php if (isset($this->error) === true) : ?>
                <div class="alert alert-danger">
                    <?= $this->error ?>
                </div>
            <?php endif; ?>
        </div>

    </div>
</div>
