<?php  $user = \System\Auth\UserSession::getInstance()->getIdentity();?>
<div class="verticalAdminMenu col-2 no-padding-right">
  <div class="admin-label">
    <span>Course</span>Network
  </div>
  <ul class="clearfix">
    <li><a href="/user/main" <?php echo ($_SERVER['REQUEST_URI'] == '/user/main') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>My profile</a></li>
    <li><a href="/user/setting" <?php echo ($_SERVER['REQUEST_URI'] == '/user/setting') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Setting</a></li>
    <li><a href="/user/portfolio" <?php echo ($_SERVER['REQUEST_URI'] == '/user/portfolio') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Portfolio</a></li>
    <li><a href="/user/jobsstatus" <?php echo ($_SERVER['REQUEST_URI'] == '/user/jobsstatus') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Job status</a></li>
    <li><a href="/user/news" <?php echo ($_SERVER['REQUEST_URI'] == '/user/news') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>News</a></li>
    <li><a href="/user/menuinfo" <?php echo ($_SERVER['REQUEST_URI'] == '/user/menuinfo') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Menu Info</a></li>
   </ul>
</div>





