<div class="verticalUserMenu col-2 no-padding-right">
  <ul class="clearfix">
    <li><a href="/user/main">My profile</a></li>
    <li><a href="/user/setting">Setting</a></li>
    <li><a href="/user/portfolio">Portfolio</a></li>
    <li><a href="/user/workdiary">Work Diary</a></li>
    <li><a href="/user/jobsstatus">Jobs Status</a></li>
    <li><a href="/user/menuinfo">Menu Info</a></li>
    <li><a href="/admin/users">Messagess</a></li>
  </ul>
  <div class="verticalUserMenu-img ">
    <img src="/assets/img/user-page/avatar/avatar.jpg"  alt="avatar">
    <?php  if (\System\Auth\UserSession::getInstance()->getIdentity() !== null) :?>
    <p><?php echo (\System\Auth\UserSession::getInstance()->getIdentity()->getEmail());?></p>
    <?php endif; ?>
  </div>
  </div>