<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand nav-logo" href="/"><span class="text-blue">Course</span>Network</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar"></ul>
        <ul class="navbar-nav navbar-toggler-right">
            <li class="nav-item active">
                <a class="nav-link" href="/users/login">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/users/register">Register</a>
            </li>
        </ul>
    </div>
</nav>