<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Navbar</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="/projects/create">Post a job</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/projects/search">Find a Job</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/freelancers/search">Find a Freelancer</a>
            </li>


            <li class="nav-item active">
                <a class="nav-link" href="/admin/main">Admin Panel</a>
            </li>
        </ul>

        <ul class="navbar-nav navbar-toggler-right">
            <li class="nav-item active">
                <a class="nav-link" href="/users/logout">Logout</a>
            </li>
        </ul>
    </div>
</nav>