<div class="row">
    <div class="offset-md-3 col-md-6">
        <form action="/users/login" method="post">
            <div class="form-group">
                <label for="email">User email</label>
                <input type="text" class="form-control" name="email" id="email" placeholder="example: youremail@mail.com">
            </div>
            <div class="form-group">
                <label for="password">User password</label>
                <input type="password" class="form-control" name="password" id="password">
            </div>

            <div class="text-right">
                <button class="btn btn-primary">Log in</button>
            </div>
        </form>
    </div>
</div>