<div class="container">
    <section class="section-login">
        <div class="row">
            <div class="col-xl-5 col-lg-5 offset-xl-1 offset-lg-1 loginRegisterLeft no-paddings">
                <div>
                    <form action="/users/register" method="post">
                        <h1>Join CourseNetwork</h1>
                        <hr>
                        <?php if (isset($this->error) === true) : ?>
                            <div class="alert alert-danger">
                                <?= $this->error ?>
                            </div>
                        <?php endif; ?>
                        <div class="form-group d-flex justify-content-end">
                            <label for="name">Full name</label>
                            <div class="col-xl-9 col-lg-9 no-padding-right">
                                <input type="text" class="form-control" name="name" id="name" <?php if(isset($_POST['name']) && empty($this->registerErrors['name'])) { echo 'value="' . $_POST['name'] . '"'; } ?> >
                                <?php if (isset($this->registerErrors['name']) === true) : ?>
                                    <div class="alert alert-danger regist-alerst">
                                        <?= $this->registerErrors['name'] ?>
                                    </div>
                                <?php endif; ?>
                                <small id="nameHelp" class="form-text text-muted">The name can't start with a number and contain special symbols.</small>
                            </div>
                        </div>

                        <div class="form-group d-flex justify-content-end">
                            <label for="email">Your email</label>
                            <div class="col-xl-9 col-lg-9 no-padding-right">
                                <input type="text" class="form-control" name="email" id="email" <?php if(isset($_POST['email']) && empty($this->registerErrors['email'])) { echo 'value="' . $_POST['email'] . '"'; } ?> placeholder="example: youremail@mail.com">
                                <?php if (isset($this->registerErrors['email']) === true) : ?>
                                    <div class="alert alert-danger regist-alerst">
                                        <?= $this->registerErrors['email'] ?>
                                    </div>
                                <?php endif; ?>
                                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                            </div>
                        </div>

                        <div class="form-group d-flex justify-content-end">
                            <label for="password">Password</label>
                            <div class="col-xl-9 col-lg-9 no-padding-right">
                                <input type="password" class="form-control" name="password" id="password">
                                <?php if (isset($this->registerErrors['password']) === true) : ?>
                                    <div class="alert alert-danger regist-alerst">
                                        <?= $this->registerErrors['password'] ?>
                                    </div>
                                <?php endif; ?>
                                <small id="passwordHelp" class="form-text text-muted">Create password at least 8 characters</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-6 member-type-icon">
                                    <input type="radio" class="form-control reg-custom-input" name="role" id="role_freelancer" value="<?= \MVC\Models\User::ROLE_FREELANCER ?>">
                                    <label for="role_freelancer">
                                        <i class="fa fa-code-fork"></i>
                                        Freelancer
                                    </label>
                                </div>

                                <div class="col-6 member-type-icon">
                                    <input type="radio" class="form-control reg-custom-input" name="role" id="role_customer" value="<?= \MVC\Models\User::ROLE_CUSTOMER ?>">
                                    <label for="role_customer">
                                        <i class="fa fa-shopping-basket"></i>
                                        Customer
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="text-right">
                            <span class="register-notice">
                                By joining, you agree to our <a href="#">Terms & Conditions</a>
                            </span>
                        </div>

                        <div class="text-right">
                            <button class="btn btn-custom1">Register</button>
                        </div>

                        <hr>
                        <div class="register-already-member d-flex justify-content-center">
                            <span>Already a member?</span>
                            <a href="/users/login">Sign in</a>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-xl-5 col-lg-5 loginRegisterRight registerRight d-flex  align-items-center">
                <div>
                    <h3>Welcome to CourseNetwork!</h3>
                    <p>Here you'll find the most talented gurus and the best freelance jobs on the market.</p>
                    <h3>Collaborate with ease.</h3>
                    <p>Use our work room tools to easily manage your team, workload, and hires.</p>
                    <h3>Pay and get paid without worry.</h3>
                    <p>SafePay and other payment security features ensure simple and safe transactions.</p>
                </div>
            </div>
        </div>
    </section>
</div>