<div class="search-page-header">
    <div class="container">
        <h1>Find & Hire Freelancers
            <br>
            <span>Search 3,603,454 freelancers being offered. Submit a free quote and get hired today!</span>
        </h1>
    </div>
</div>
<div class="light-gray-wrap project-search-wrap">
    <?= $this->layout('partial/search-tabs') ?>
    <div class="container">
        <div class="row search-page-content">
            <div class="sidebarProjectFilter">
                <div class="sidebarBox">
                    <h2 class="iconCategoriesBlue">Categories</h2>
                    <hr>
                    <ul class="sidebarFilter">
                        <li><a href="/freelancers/search/" class="active">All categories<span
                                        class="total-number">(<?= $this->countAll ?>)</span></a></li>
                        <?php foreach ($this->categories as $category): ?>
                            <?php /** @var \MVC\Models\Category $category */ ?>
                            <li><a href="/freelancers/category/<?= $category->getId() ?>/"><?= $category->getName() ?>
                                    <span class="total-number">(<?= $category->getCountFreelancers() ?>)</span></a></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="sidebarBox jobType">
                    <h2 class="iconBubbleBlue">Job type</h2>
                    <hr>
                    <ul class="sidebarFilter">
                        <li>
                            <label class="control control--radio radio-inline">
                                <input type="radio" value="" checked="checked">All
                                <div class="control__indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="control control--radio radio-inline">
                                <input type="radio" value="">Fixed
                                <div class="control__indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="control control--radio radio-inline">
                                <input type="radio" value="">Per Hour
                                <div class="control__indicator"></div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div class="sidebarBox">
                    <h2 class="iconStarBlue">Show only</h2>
                    <hr>
                    <ul class="sidebarFilter">
                        <li>
                            <label class="control control--checkbox">
                                <input type="checkbox" value="">Is online
                                <div class="control__indicator"></div>
                            </label>
                        </li>
                        <li>
                            <label class="control control--checkbox">
                                <input type="checkbox" value="">Freelancers with portfolio
                                <div class="control__indicator"></div>
                            </label>
                        </li>
                    </ul>
                </div>
                <div class="sidebarBox">
                    <h2 class="iconCoinBlue">Rate/Hr</h2>
                    <hr>
                    <ul class="sidebarFilter">
                        <li><a href="#" class="active">Any Rate</a></li>
                        <li><a href="#" class="">$0 - $25</a></li>
                        <li><a href="#" class="">$25 - $50</a></li>
                        <li><a href="#" class="">$50 - $100</a></li>
                        <li><a href="#" class="">$100 - $200</a></li>
                        <li><a href="#" class="">$200+</a></li>
                    </ul>
                </div>
                <div class="sidebarBox">
                    <h2 class="iconStarBlue">Rating</h2>
                    <hr>
                    <ul class="sidebarFilter">
                        <li><a href="#" class="active">Any Rating</a></li>
                        <li><a href="#" class="">5 Stars</a></li>
                        <li><a href="#" class="">4+ Stars</a></li>
                        <li><a href="#" class="">3+ Stars</a></li>
                        <li><a href="#" class="">3 Less Stars</a></li>
                    </ul>
                </div>
                <div class="sidebarBox">
                    <h2 class="iconBubbleBlue">By Reviews</h2>
                    <hr>
                    <ul class="sidebarFilter">
                        <li><a href="#" class="active">Any Review</a></li>
                        <li><a href="#">3+ Review</a></li>
                        <li><a href="#">10+ Review</a></li>
                        <li><a href="#">20+ Review</a></li>
                        <li><a href="#">50+ Review</a></li>
                    </ul>
                </div>
                <div class="sidebarBox">
                    <h2 class="iconBubbleBlue">Search by tested skills</h2>
                    <hr>
                    <form action="">
                        <label for="searchJobselectSkill"></label>
                        <select id="searchJobselectSkill" class="custom-select">
                            <option selected>Select one</option>
                            <option value="1">Web Design</option>
                            <option value="2">Drupal</option>
                            <option value="3">SQL</option>
                            <option value="4">Word</option>
                            <option value="5">Exel</option>
                            <option value="6">Something...</option>
                            <option value="7">Another skill</option>
                            <option value="8">Super Skill</option>
                        </select>
                        <br>
                        <input type="submit" class="btn-custom1 sidebar-button" value="Go">
                    </form>
                </div>
            </div>
            <div class="projectList">
                <!-- Search box -->
                <header class="clearfix">
                    <form action="" id="project-search-form" class="search-box">
                        <div class="row">
                            <div class="col-10 search-input no-padding-right">
                                <input type="search" id="keyword" placeholder="Search Freelancers...">
                            </div>
                            <div class="col-2 search-button no-padding-left">
                                <input type="submit" class="btn-custom1" value="Search">
                            </div>
                        </div>
                    </form>
                </header>

                <!-- Sorting -->

                <div>
                    <div class="col-6">
                        <div class="row justify-content-start align-items-center">
                            <div class="sortBy">Sort by</div>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Relevance
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Relevance</a>
                                    <a class="dropdown-item" href="#">Total Earnings</a>
                                    <a class="dropdown-item" href="#">Rating</a>
                                    <a class="dropdown-item" href="#">Rate</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Freelancers list -->

                <div class="freelancers-list-result">

                    <!-- Freelancer-item -->
                    <?php foreach ($this->freelancers as $freelancer): ?>
                        <?php /** @var \MVC\Models\Freelancer $freelancer */ ?>
                        <div class="freelancer-item">
                            <div class="freelancer-item__header clearfix">
                                <h2 class="title float-left"><a href="#"><?= $freelancer->getUser()->getName() ?></a>
                                </h2>
                                <span class="float-right rating-amount">(<?= $freelancer->getRating() ?>)</span>
                                <span class="freelancer-rating float-right">
                <span style="width: 100%;"></span>
              </span>
                            </div>
                            <div class="freelancer-item-meta">
                                <div class="clearfix">
                                    <div class="freelancer-photo float-left">
                                        <a href="#"><img
                                                    src="/assets/img/projects-freelancers-search-page/freelancer-random.jpg"
                                                    alt=""></a>
                                    </div>
                                    <div class="freelancer-meta float-right">
                                        <ul class="freelancer-item-attributes clearfix">
                                            <li><?= $freelancer->getRate() ?>$ / Hr</li>
                                            <li><a href="#"><?= $freelancer->getJobCount() ?> review(s)</a></li>
                                        </ul>
                                        <p class="desc"><?= $freelancer->getDescription() ?>
                                        </p>
                                    </div>
                                </div>
                                <ul class="tags">
                                    <?php if ($freelancer->getCategory() !== null) : ?>
                                        <li>
                                            <a href="/freelancers/category/<?= $freelancer->getCategory()->getId() ?>/"><?= $freelancer->getCategory()->getName() ?></a>
                                        </li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>

            </div>
        </div>
    </div>
</div>