<?php

namespace System\ORM;

use System\Database\Statement\Select;

/**
 * Class Criteria
 * @package System\ORM
 */
class Criteria extends Select
{

    /**
     * @var array
     */
    protected $repository;

    /**
     * Criteria constructor.
     * @param Repository $repository
     */
    public function __construct($repository)
    {
        parent::__construct();
        $this->repository = $repository;
        $this->from($repository->getStorage());
    }

    /**
     * @param array $columns
     * @return string
     */
    protected function encodeColumns(array $columns)
    {
        $columns = array_map(
            function ($column) {
                return $this->repository->getProperty($column);
            },
            $columns
        );

        return '`' . implode('`, `', $columns) . '`';
    }

    /**
     * @param $field
     * @param $delimiter
     * @param $value
     * @return $this
     */
    public function where($field, $delimiter, $value)
    {
        return parent::where(
            $this->repository->getProperty($field),
            $delimiter,
            $value
        );
    }

    /**
     * @param $field
     * @param $values
     * @return $this
     */
    public function whereIn($field, $values)
    {
        return parent::whereIn($this->repository->getProperty($field), $values); // TODO: Change the autogenerated stub
    }

    /**
     * @param $field
     * @param $values
     * @return $this
     */
    public function whereNotIn($field, $values)
    {
        return parent::whereIn($this->repository->getProperty($field), $values); // TODO: Change the autogenerated stub
    }

}