<div class="row">
  <?php $this->layout('user/menu'); ?>
  <div class="jobs-user ">
    <table class="table table-bordered offset-1">
      <thead>
      <tr>
        <th>#</th>
        <th>Name Project</th>
        <th>Customer</th>
        <th>Start</th>
        <th>Finish</th>
        <th>Status</th>
        <th>Payment</th>
      </tr>
      </thead>
      <tbody>
      <tr class="bg-danger">
        <th scope="row">1</th>
        <td>internet Shop</td>
        <td>Mark Zukerberg</td>
        <td>12 January 2017</td>
        <td>12 March 2017</td>
        <td>completed</td>
        <td>is not paid</td>
      </tr>
      <tr  class="bg-warning">
        <th scope="row">2</th>
        <td>Game "World War I" </td>
        <td>Otto Bismark</td>
        <td>10 December 2017</td>
        <td>1 May 2017</td>
        <td>in progress</td>
        <td>is not paid</td>
      </tr>
      <tr class="bg-success">
        <th scope="row">3</th>
        <td>Event calendar</td>
        <td>Jacob Thornton</td>
        <td>1 November 2016</td>
        <td>25 December 2017</td>
        <td>completed</td>
        <td>paid</td>
      </tr>
      <tr  class="bg-warning">
        <th scope="row">4</th>
        <td>Lending Page</td>
        <td>Larry Bird</td>
        <td>10 January 2017</td>
        <td>20 February 2017</td>
        <td>in progress</td>
        <td>is not paid</td>
      </tr>
      </tbody>
    </table>
  </div>
  </div>

