<div class="row">
    <?php $this->layout('user/menu'); ?>
    <div class="menuinfo-user col-sm-10">
        <div class="offset-2 col-sm-8">
            <p><b>My profile -</b>
                It all starts by creating a great profile and submitting a compelling job proposal. Getting freelance work online is a lot like traditional searching — you submit applications on projects, then impress potential clients before being offered the project.
                Creating an outstanding freelancer profile to showcase your business. Think of it as an introduction, resume, and marketing brochure rolled into one, highlighting your: professional skills, experience, and portfolio; education and accomplishments; and online skills test results. The best profiles are complete, well-written, error-free, and feature a professional, friendly-looking picture.
                Sending the client a compelling proposal. This will greatly increase your likelihood of getting an interview, so consider making sure yours is: professional, well-written, and error-free; tailor-made for the work you're seeking; and a true representation of your strengths and skills.
            </p>
            <p><b>Setting - </b>
                Account Settings allows you to view and edit your global Settings and Preferences.
                Here you can edit your username and Password,other information
                (General Settings), security settings, email notifications,
                manage your trusted devices  interacts with websites.
            </p>
            <p><b>Portfolio - </b>
                This type of portfolio management specially addresses the issues with spending on the development of innovative capabilities in terms of potential ROI, reducing investment overlaps in situations where reorganization or acquisition occurs, or complying with legal or regulatory mandates. The management issues with project-oriented portfolio management can be judged by criteria such as ROI, strategic alignment, data cleanliness, maintenance savings, suitability of resulting solution and the relative value of new investments to replace these projects.
                Information Technology portfolio management as a systematic discipline is more applicable to larger IT organizations; in smaller organizations its concerns might be generalized into IT planning and governance as a whole.
            </p>
            <p><b>Work Diary - </b>
                The calendar extension allows you to manage events and display them in a calendar or event list on the website. Unlike articles that are associated with a particular page, events are organized in calendars, which allows you to easily group, categorize or export them.
            </p>
            <p><b>Job Status - </b>
                If you are working and requesting unemployment benefits, you must report your earnings and the hours you worked for each week you request benefit payments. There are no exceptions to what TWC considers “work.”
                Work is any type of service for pay, including but not limited to:
                Full-time or part-time work
                Paid orientation and training
                Temporary and seasonal work
                Commissions and tips
                Contract labor and side jobs, including but not limited to day labor, mowing lawns, yard work and cleaning houses
                Financial compensation from bartering
                U.S. military service, National Guard, or reservist duties
                Self-employment
            </p>
            <p><b>Messages - </b>
                When you send a message to another application, you are not informed of any problems unless you complete the Report field to indicate the feedback that you require. See Structure of the report field for the options available.
                Queue managers always put report messages on an application's reply-to queue and it is recommended that your own applications do the same. When you use the report message facility, specify the name of your reply-to queue in the message descriptor of your message; otherwise, the MQPUT call fails.
            </p>
        </div>
    </div>
</div>

