
<div class="row">
  <?php $this->layout('user/menu'); ?>
  <div class="news-user col-sm-10">
    <?php  if (\System\Auth\UserSession::getInstance()->getIdentity() !== null) :?>
    <h1> Hello <?php echo (\System\Auth\UserSession::getInstance()->getIdentity()->getName());?>&nbsp;!!!</h1>
    <?php endif;?>
    <h2>Getting Paid in Ukraine: Setting Up Wire Transfers as a Private Entrepreneur</h2>
        <img class="offset-2 col-sm-8" src="/assets/img/user-page/main/background-main.jpg"  alt="avatar">
        <h3>THE BASICS</h3>
       <p> Currently, there is a compliant way for UA freelancers to receive funds via wire transfer to a private entrepreneur bank account.
         The new currency controls say that Ukrainian freelancers registered as private entrepreneurs (PE) can use an invoice they complete
         themselves instead of a Confirmation of Services and User Agreement, which was required in the past.
         Setting up your withdrawal method even before you have an available balance is important as it takes three days to activate
         a newly added bank account.
        <p>

        <h3>ADDING AND VERIFYING WIRE TRANSFER (PE BANK ACCOUNT)</h3>

       <p> It is essential that you enter your bank information 100% accurately to avoid fund routing problems.
        Once you add and save it, you cannot edit your bank account and SWIFT code.
        To update these numbers, or to use a different account, you must add a new account
        (then remove the old one if it is incorrect or you no longer need it).
        Contact your bank if you’re not sure you have the correct information or if you received an error when you tried to enter it in the Upwork system.
        <p>
              <h3>HOW CAN I FILL IT OUT?</h3>

              <p>Every field of the invoice template is required, so you may not want to change anything, unless otherwise requested by the bank or instructed by your advisors. Sometimes, identical provisions may be viewed differently by different branch offices of the same bank. Thus, if in the process of checking the invoice you are requested to add or remove some non-essential things from the invoice, it may be easier to make the change than to engage in a long and unsuccessful discussion. To use the template, you will fill in the following details by yourself:
             <ul>
             <li> (1) invoice number (it is up to you, for example, simply change the date of invoice each time – 2301/1);
             </li>
              <li>
              (2) invoice date (1-3 days before the payment date);
              </li>
              <li>
              (3) executor details — specify that you are an individual entrepreneur, write your last name, name and patronymic, registration address and identification number;
              </li>

              </ul>
             </p>

  </div>
</div>
