<div class="row">
  <?php $this->layout('user/menu'); ?>
  <div class="portfolio-user">
      <div class="row">
      <div class="col-md-2 offset-2">
        <div class="thumbnail">
          <a href="http://devsaran.com/drupal-theme/black-premium">
            <img src="/assets/img/user-page/portfolio/p1.png" >
            <div class="caption">
              <p>Black Premium Theme is a great looking Drupal 7 theme.
                The theme is not dependent on any core theme.

              </p>
            </div>
          </a>
        </div>
        </div>
        <div class="col-md-2">
          <div class="thumbnail">
            <a href="http://devsaran.com/drupal-theme/simple-corporate">
              <img src="/assets/img/user-page/portfolio/p2.png">
              <div class="caption">
                <p>Simple Corporate is a great looking Drupal 7 theme.
                  The theme is not dependent on any core theme. </p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-2">
          <div class="thumbnail">
            <a href="http://devsaran.com/drupal-theme/business-theme">
              <img src="/assets/img/user-page/portfolio/p3.png">
              <div class="caption">
                <p>Business is a great looking Drupal 7 theme.
                  Its very light weight with modern look and fee.
                </p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-2">
          <div class="thumbnail">
            <a href="http://devsaran.com/drupal-theme/nexus-theme">
              <img src="/assets/img/user-page/portfolio/p4.png">
              <div class="caption">
                <p>
                  Nexus Theme is a responsive business Drupal theme created by Devsaran.
                </p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-2 offset-2">
          <div class="thumbnail">
            <a href="http://devsaran.com/drupal-theme/dark-elegant">
              <img src="/assets/img/user-page/portfolio/p5.png">
              <div class="caption">
                <p>
                  Dark Elegant is another beautiful and very powerful premium Drupal 7 theme
                </p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-2">
          <div class="thumbnail">
            <a href="http://devsaran.com/drupal-theme/clean-theme">
              <img src="/assets/img/user-page/portfolio/p6.png">
              <div class="caption">
                <p>
                  The theme is not dependent on any core theme.
                  Its very light weight with modern look and feel.
                </p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-2">
          <div class="thumbnail">
            <a href="http://.devsaran.com/drupal-theme/splendio">
              <img src="/assets/img/user-page/portfolio/p7.png">
              <div class="caption">
                <p>Splendio is a great looking Drupal 7 theme which is perfect for all sorts of bloggers
                  and that includes a very unique and engaging design for your readers</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-2">
          <div class="thumbnail">
            <a href="http://devsaran.com/drupal-theme/professional-theme">
              <img src="/assets/img/user-page/portfolio/p8.png">
              <div class="caption">
                <p>
                  The theme is not dependent on any core theme.
                  Its very light weight with modern look and feel.
                </p>
              </div>
            </a>
          </div>
        </div>



  </div>
</div>
</div>
