<div class="row">
  <?php $this->layout('user/menu'); ?>
  <div class="setting-user ">
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-1 col-form-label">Full name</label>
      <div class="col-6">
        <input class="form-control" type="text" value="Artisanal kale">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-1 col-form-label">Login</label>
      <div class="col-6">
        <input class="form-control" type="search" value="How do I shoot web">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-email-input" class="col-1 col-1 offset-1 col-form-label">Email</label>
      <div class="col-6">
        <input class="form-control" type="email" value="bootstrap@example.com">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-url-input" class="col-1 col-1 offset-1 col-form-label">Site</label>
      <div class="col-6">
        <input class="form-control" type="url" value="https://getbootstrap.com">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-tel-input" class="col-1 col-1 offset-1 col-form-label">Telephone</label>
      <div class="col-6">
        <input class="form-control" type="tel" value="+380-(55)-555-5555">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-1 col-form-label">Skype</label>
      <div class="col-6">
        <input class="form-control" type="text" value="hunter2" ">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-number-input" class="col-1 col-1 offset-1 col-form-label">Password</label>
      <div class="col-6">
        <input class="form-control" type="password" value="42" ">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-number-input" class="col-1 col-1 offset-1 col-form-label"></label>
      <div class="col-2">
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>
    </div>

  </div>
</div>
