<div class="row">
  <?php $this->layout('user/menu'); ?>
  <div class="portfolio-user">
    <div class="offset-1" id="calendar"></div>

    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-2 col-form-label">Event</label>
      <div class="col-8">
        <input class="form-control" type="text">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-2 col-form-label">Date</label>
      <div class="col-8">
        <input class="form-control" type="date">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-2 col-form-label">Section</label>
      <div class="col-8">
        <input class="form-control" type="text">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-2 col-form-label">Place</label>
      <div class="col-8">
        <input class="form-control" type="text">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-2 col-form-label">Time</label>
      <div class="col-8">
        <input class="form-control" type="time">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-number-input" class="col-1 col-1 offset-2 col-form-label"></label>
      <div class="col-2">
        <button class="btn btn-primary" type="submit">Add</button>
      </div>
    </div>
  </div>
  </div>
<script src="/assets/js/calendar.js"></script>
