<form action="/admin/create-category" method="post">

    <div class="form-group">
        <label for="name">Category name</label>
        <input type="text" name="name" class="form-control" id="name">
    </div>

    <div class="form-group">
        <label for="description">Category description</label>
        <textarea name="description" class="form-control" id="description" cols="30" rows="10"></textarea>
    </div>

    <button>Create</button>

</form>