<div class="verticalAdminMenu col-2 no-padding-right">
  <ul class="clearfix">
    <li><a href="/admin/main">Main page</a></li>
    <li><a href="/admin/users">List of users</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>
    <li><a href="/admin/users">Menu item</a></li>

  </ul>
</div>