<div class="verticalAdminMenu col-2 no-padding-right">
  <div class="admin-label">
    <span>Course</span>Network
  </div>
  <ul class="clearfix">
    <li><a href="/admin/main" <?php echo ($_SERVER['REQUEST_URI'] == '/admin/main') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Main page</a></li>
    <li><a href="/admin/users" <?php echo ($_SERVER['REQUEST_URI'] == '/admin/users') ? "class='active'" : ""; ?>><i class="fa fa-users" aria-hidden="true"></i>List of users</a></li>
    <li><a href="/admin/customers" <?php echo ($_SERVER['REQUEST_URI'] == '/admin/customers') ? "class='active'" : ""; ?>><i class="fa fa-customers"></i>List of customers</a></li>
    <li><a href="/admin/freelancers" <?php echo ($_SERVER['REQUEST_URI'] == '/admin/freelancers') ? "class='active'" : ""; ?>><i class="fa fa-freelancers"></i>List of freelancers</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
    <li><a href="/admin/users"><i class="fa fa-lock"></i>Menu item</a></li>
  </ul>
</div>
