<div class="container">
    <div class="row project-detail">
        <h1 class="title float-left"><?= $this->project->getName() ?></h1>
        <div class="project-list-result">
            <div class="project-info">
                <div class="project-info-box">
                    <ul class="project-item-attributes">
                        <li>Payment Type<div class="project-item-attributes-value"><?= $this->project->getWorkType() ?></div></li>
                        <li>Budget<div class="project-item-attributes-value">$<?= $this->project->getBudget() ?></div></li>
                        <li>Posted<div class="project-item-attributes-value"><?= date('d F', $this->project->getCreated()) ?></div></li>
                        <li>Proposals<div class="project-item-attributes-value"><?= $this->project->getRequestsCount() ?></div></li>
                    </ul>
                </div>
                <div class="project-item__header">
                    <a href="" class="project-item__bookmark float-right"></a>
                </div>
                <div class="project-info-proposal-box float-right">
                    <a href="#" class="btn btn-custom1 button-send-proposal proposal-link">Send Proposal</a>
                </div>
            </div>

            <?php if (isset($this->errorUser) === true) : ?>
                <div class="alert alert-danger proposal-form">
                    <?= $this->errorUser ?>
                </div>
            <?php else: ?>
            <div class="row vert-mg-proposal proposal-form">
                <?php if (isset($this->error) === true) : ?>
                    <div class="alert alert-danger">
                        <?= $this->error ?>
                    </div>
                <?php endif; ?>
                <div class="col-10 pd-20">
                    <div class="row">
                        <div class="col-9">
                            <h1>Send your Best Proposal!</h1>
                        </div>
                        <div class="col-2 pd--15">
                            <a href="#"><div class="project-request-balance">
                                    <div>Proposal Balance</div>
                                    <div class="proposals-balance">
                                        <span class="proposals-available"><?= $this->freelancer->getRequestBalance() ?></span>
                                        <span class="proposals-permissible">/<?= $this->freelancer->getPlan()->getRequestAmount() ?></span>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <hr>
                    <form action="/projects/project/<?= $this->project->getId() ?>" method="post" id="formJob">
                        <div class="createJobForm">
                            <div class="row">
                                <div class="form-group col-4">
                                    <label for="createFormBudget">Proposal Rate</label>
                                    <input type="text" name="rate" class="form-control proposal-input" id="createFormBudget" aria-describedby="emailHelp" placeholder="Proposals Rate">$
                                </div>

                                <div class="form-group col-4">
                                    <label for="createFormDeadline">Deadline</label>
                                    <div><input type="text" name="deadline" class="form-control proposal-input" id="createFormDeadline" aria-describedby="emailHelp" placeholder="When the project is doing">days</div>
                                </div>
                            </div>
                        </div>
                        <div class="createJobForm">
                            <div class="form-group">
                                <label for="createFormDescription">Description</label>
                                <textarea class="form-control" name="description" id="createFormDescription" rows="3" placeholder="Provide a more detailed description to help you get project"></textarea>
                            </div>
                        </div>

                        <div class="createJobForm">
                            <button class="btn-custom1">Post Proposal</button>
                        </div>
                    </form>
                </div>
            </div>
            <?php endif; ?>

            <div class="project-item">
                <div class="project-description-box">
                    <p class="desc"><?= $this->project->getDescription() ?></p>
                    <ul class="tags">
                        <li><a href="#"><?= $this->project->getCategory()->getName() ?></a></li>
                    </ul>
                </div>
                <div class="project-item-footer clearfix">
                    <div class="float-left client clearfix">
                        <a href="#"><img src="/assets/img/icons/user.png" class="float-left client-avatar" alt=""></a>
                        <div class="float-left">
                            <h4 class="client-name">
                                <a href="#"><?= $this->project->getCustomer()->getUser()->getName() ?></a>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row project-proposals">
            <div class="col-lg-12 project-proposals-header ">
                <div class=" col-lg-7 submitted-header">Submitted proposals (<?= $this->project->getRequestsCount() ?>)</div>
                <div class="col-lg-2 freelancers-rating-header">Raiting</div>
                <div class="col-lg-3 project-proposal-header">Proposal (USD)</div>
            </div>
            <div class="project-proposals-list col-lg-12">
                <?php if (isset($this->errorProposals)) : ?>
                    <div class="alert alert-info">
                        <?= $this->errorProposals ?>
                    </div>
                <?php else: ?>

                    <?php foreach($this->proposals as $proposal):?>
                        <?php /** @var \MVC\Models\Request $proposal */?>
                        <div class="row project-proposals-item">
                            <div class="col-lg-7 proposals-submitted">
                               <!-- <div class="col-lg-2"><?php //= $proposal->getFreelancerId()->getUser()->getAvatar()?></div>-->
                                <div class="col-lg-12">
                                    <a href="#"><?= $proposal->getFreelancerId()->getUser()->getName() ?></a>
                                </div>
                                <div class="col-lg-12"><?= $proposal->getRequestText() ?></div>
                            </div>
                            <div class="col-lg-2 proposals-freelancers-rating">
                                <?= $proposal->getFreelancerId()->getRating() ?>
                            </div>
                            <div class="col-lg-3 project-proposal">
                                Proposal <?= $proposal->getRate() ?>$ for <?= $proposal->getDeadline() ?> days
                            </div>
                        </div>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
        </div>
    </div>

</div>


