<div class="container">
    <div class="row vert-mg-proposal">
        <?php if (isset($this->error) === true) : ?>
            <div class="alert alert-danger">
                <?= $this->error ?>
            </div>
        <?php endif; ?>
        <div class="col-10 pd-20">
            <div class="row">
                <div class="col-9">
                    <h1>Send your Best Proposal!</h1>
                </div>
                <div class="col-2 pd--15">
                    <a href="#"><div class="project-request-balance">
                            <div>Proposal Balance</div>
                            <div class="proposals-balance">
                                <span class="proposals-available">5</span><span class="proposals-permissible">/8</span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <hr>
            <form action="request" method="post" id="formJob">
                <div class="createJobForm">
                    <div class="row">
                        <div class="form-group col-4">
                            <label for="createFormBudget">Proposal Rate</label>
                            <input type="text" name="rate" class="form-control proposal-input" id="createFormBudget" aria-describedby="emailHelp" placeholder="Proposals Rate">$
                        </div>

                        <div class="form-group col-4">
                            <label for="createFormDeadline">Deadline</label>
                            <div><input type="text" name="deadline" class="form-control proposal-input" id="createFormDeadline" aria-describedby="emailHelp" placeholder="When the project is doing">days</div>
                        </div>
                    </div>
                </div>
                <div class="createJobForm">
                    <div class="form-group">
                        <label for="createFormDescription">Description</label>
                        <textarea class="form-control" name="description" id="createFormDescription" rows="3" placeholder="Provide a more detailed description to help you get project"></textarea>
                    </div>
                </div>

                <div class="createJobForm">
                    <button class="btn-custom1">Post Proposal</button>
                </div>
            </form>
        </div>

    </div>

    </div>
