<div class="container vert-mg-60">
  <div class="row">
    <div class="col-3">
      <h5>Search Projects</h5>
    </div>
    <div class="col-9">
      <form action="" id="project-search-form">
        <div class="row">
          <div class="col-10">
            <input type="search" id="keyword" placeholder="Search projects...">
          </div>
          <div class="col-2">
            <input type="submit" class="btn-custom1" value="Search">
          </div>
        </div>
      </form>
    </div>
  </div>

  <div class="row">
    <div class="col-3 sidebarProjectFilter">
      <div class="sidebarBox">
        <h2 class="iconBubbleBlue">Experience level</h2>
        <hr>
        <ul class="sidebarFilter">
          <li><label><input type="checkbox" value="">Entry level($)</label></li>
          <li><label><input type="checkbox" value="">Intermediate level($$)</label></li>
          <li><label><input type="checkbox" value="">Expert level($$$)</label></li>
        </ul>
      </div>

      <div class="sidebarBox jobType">
        <h2 class="iconBubbleBlue">Job type</h2>
        <hr>
        <ul class="sidebarFilter">
          <li><label class="radio-inline"><input type="radio" value="">All</label></li>
          <li><label class="radio-inline"><input type="radio" value="">Fixed</label></li>
          <li><label class="radio-inline"><input type="radio" value="">Per Hour</label></li>
        </ul>
      </div>

      <div class="sidebarBox">
        <h2 class="iconCategoriesBlue">Categories</h2>
        <hr>
        <ul class="sidebarFilter">
          <li><a href="#">All categories</a><span class="float-right">204</span></li>
          <li><a href="#">Design</a><span class="float-right">204</span></li>
          <li><a href="#">Web Development</a><span class="float-right">204</span></li>
          <li><a href="#">Business support</a><span class="float-right">204</span></li>
          <li><a href="#">Video, phote & audio</a><span class="float-right">204</span></li>
          <li><a href="#">Writing</a><span class="float-right">204</span></li>
          <li><a href="#">Software development</a><span class="float-right">204</span></li>
          <li><a href="#">Marketing & PR</a><span class="float-right">204</span></li>
          <li><a href="#">Admin</a><span class="float-right">204</span></li>
          <li><a href="#">Search Marketing</a><span class="float-right">204</span></li>
          <li><a href="#">Social Media</a><span class="float-right">204</span></li>
          <li><a href="#">Mobile</a><span class="float-right">204</span></li>
          <li><a href="#">Translations</a><span class="float-right">204</span></li>
          <li><a href="#">Creative Arts</a><span class="float-right">204</span></li>
          <li><a href="#">Tutorials</a><span class="float-right">204</span></li>
          <li><a href="#">Extraordinary</a><span class="float-right">204</span></li>
        </ul>
      </div>
    </div>


    <div class="col-9 projectList">
      <div>
        <h1 id="listProjectsHeading">Freelance Projects
        <span>4459 projects found</span>
        </h1>
        <div class="col-6">
          <div class="row justify-content-start align-items-center">
            <div class="sortBy">Sort by</div>
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Latest
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Latest</a>
                <a class="dropdown-item" href="#">Popularity</a>
                <a class="dropdown-item" href="#">Ending soon</a>
                <a class="dropdown-item" href="#">Budget</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>