<div class="search-page-header">
    <div class="container">
        <h1>Find Freelance Projects
            <br>
            <span>Search over 4,875 job postings in any category. Submit a free quote and get hired today!</span>
        </h1>
    </div>
</div>
<div class="light-gray-wrap project-search-wrap">
    <?= $this->layout('partial/search-tabs') ?>
    <div class="container">
        <div class="row search-page-content">
            <div class="sidebarProjectFilter">
                <form action=""   method="post">
                    <div class="sidebarBox jobType">
                        <h2 class="iconBubbleBlue">Job type</h2>
                        <hr>
                        <ul class="sidebarFilter">
                            <li>
                                <label class="control control--radio radio-inline">
                                    <input type="radio" value=""  name="work_type" checked>All
                                    <div class="control__indicator"></div>
                                </label>
                            </li>
                            <li>
                                <label class="control control--radio radio-inline">
                                    <input type="radio" value="<?= \MVC\Models\Project::TYPE_FIXED?>" name="work_type">Fixed
                                    <div class="control__indicator"></div>
                                </label>
                            </li>
                            <li>
                                <label class="control control--radio radio-inline">
                                    <input type="radio" value="<?= MVC\Models\Project::TYPE_PER_HOUR?>" name="work_type">Per Hour
                                    <div class="control__indicator"></div>
                                </label>
                            </li>
                        </ul>
                    </div>
                    <div class="sidebarBox">
                        <h2 class="iconCategoriesBlue">Categories</h2>
                        <hr>
                        <ul class="sidebarFilter">
                            <li><a href="/projects/search/" class="active">All categories
                                    <span class="total-number">(<?= $this->countAll ?>)</span>
                                </a>
                            </li>
                            <?php foreach ($this->categories as $category): ?>
                                <?php /** @var \MVC\Models\Category $category */ ?>
                                <li><a href="/projects/category/<?= $category->getId() ?>/">
                                        <input type="radio" value="<?= $category->getId() ?>" name="category" />
                                        <?= $category->getName() ?>
                                        <span class="total-number">(<?= $category->getCount() ?>)</span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="col-2 search-button no-padding-left">
                        <input type="submit" class="btn-custom1" value="Search">
                    </div>
                </form>
            </div>
            <div class="projectList">
                <!-- Search box -->
                <header class="clearfix">
                    <form action="" id="project-search-form" class="search-box" method="post">
                        <div class="row">
                            <div class="col-10 search-input no-padding-right">
                                <input type="search" id="keyword" placeholder="Search projects..." name="search">
                            </div>
                            <div class="col-2 search-button no-padding-left">
                                <input type="submit" class="btn-custom1" value="Search">
                            </div>
                        </div>
                    </form>
                </header>
                <!-- Sorting -->
                <div>
                    <div class="col-6">
                        <div class="row justify-content-start align-items-center">
                            <div class="sortBy">Sort by</div>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Latest
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Latest</a>
                                    <a class="dropdown-item" href="#">Popularity</a>
                                    <a class="dropdown-item" href="#">Ending soon</a>
                                    <a class="dropdown-item" href="#">Budget</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if (count($this->projects) > 0) : ?>
                    <!-- Project list -->
                    <div class="project-list-result">
                        <!-- Project-item -->
                        <?php foreach ($this->projects as $project): ?>
                            <?php /** @var \MVC\Models\Project $project */ ?>
                            <div class="project-item">
                                <div class="project-item__header clearfix">
                                    <h2 class="title float-left"><a
                                            href="/projects/project/<?= $project->getId() ?>"><?= $project->getName() ?></a>
                                    </h2>
                                    <a href="" class="project-item__bookmark float-right"></a>
                                </div>
                                <div class="project-item-meta">
                                    <ul class="project-item-attributes">
                                        <li><?= $project->getWorkType() ?></li>
                                        <li><?= $project->getBudget() ?>$</li>
                                        <li>Posted <?= date('d F', $project->getCreated()) ?></li>
                                        <li><?= $project->getRequestsCount() ?> Proposals</li>
                                    </ul>
                                    <p class="desc"><?= $string = stripslashes(substr($project->getDescription(), 0, 300)) ?>
                                    </p>
                                    <ul class="tags">
                                        <li>
                                            <a href="/projects/category/<?= $project->getCategory()->getId() ?>/"><?= $project->getCategory()->getName() ?></a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="project-item-footer clearfix">
                                    <div class="float-left client clearfix">
                                        <a href="#"><img src="/assets/img/icons/user.png" class="float-left client-avatar"
                                                         alt=""></a>
                                        <div class="float-left">
                                            <h4 class="client-name">
                                                <a href="#"><?php//= $project->getCustomer()->getUser()->getName() ?></a>
                                            </h4>
                                        </div>
                                    </div>
                                    <div class="float-right send">
                                        <a href="/projects/project/<?= $project->getId() ?>/"
                                           class="btn btn-custom1 button-send-proposal">Send Proposal</a>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        <!-- Project-item -->
                    </div>
                <?php else: ?>
                    <div class="text-center text-muted">
                        <h3>Nothing found</h3>
                    </div>
                <?php endif; ?>

            </div>
        </div>
    </div>
</div>