<?php var_dump($this->portfolio);die; ?>
<div class="row">
  <?php $this->layout('using/menu'); ?>
  <div class="portfolio-user col-sm-10">

    <form action="/using/portfolio" method="post">
      <input type="hidden" name="addButton" value="addButton">
    <button  class="btn btn-primary col-2 offset-9" type="submit">Add to portfolio</button>
    </form>
    <div class="row">
        <div class="thumbnail col-3 offset-1">
            <img src="/assets/img/user-page/portfolio/p1.png" >
            <div class="caption">
              <a href="http://devsaran.com/drupal-theme/black-premium" >theme</a>
               <p>Theme is a great looking Drupal 7 theme.
                The theme is not dependent on any core theme.
              </p>
            </div>
        </div>


  </div>
</div>
</div>
