
<div class="row">
  <?php $this->layout('using/menu'); ?>
  <?php  if (\System\Auth\UserSession::getInstance()->getIdentity() !== null) :?>
  <?php  $user = \System\Auth\UserSession::getInstance()->getIdentity();?>
  <?php endif;?>
  <div class="setting-user col-sm-10">
    <h3 class="offset-1"> Edit Your personal setting :</h3>
    <form   action="/using/setting"
         enctype="multipart/form-data" method="post">
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-1 col-form-label">Full name</label>
      <div class="col-6">
        <input class="form-control " type="text" name ="name" value="<?= $user->getName()? : '';?>"
                 placeholder="Input your full name ">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-1 col-form-label">Login</label>
      <div class="col-6">
        <input class="form-control" type="email" name="login" value="<?= $user->getEmail()? : '';?>"
               placeholder="Login must be equal exmpl@example.com">
      </div>
    </div>

    <div class="form-group row">
      <label for="example-url-input" class="col-1 col-1 offset-1 col-form-label">Site</label>
      <div class="col-6">
        <input class="form-control" type="url" name="site" placeholder="Input your site" value="<?=$user->getSite()?:'';?>">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-tel-input" class="col-1 col-1 offset-1 col-form-label">Telephone</label>
      <div class="col-6">
        <input class="form-control" type="tel" name="phone"
               value="<?=$user->getPhone()?:'';?>" placeholder="Input your phone (example +380-(55)-555-5555)">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-text-input" class="col-1 col-1 offset-1 col-form-label">Skype</label>
      <div class="col-6">
        <input class="form-control" type="text" name="skype"
               value="<?=$user->getSkype()? :'';?>"placeholder="Input your Skype name">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-number-input" class="col-1 col-1 offset-1 col-form-label">Password</label>
      <div class="col-6">
        <input class="form-control" type="password" name="password"
               placeholder="Input your safe password">
      </div>
    </div>
    <div class="form-group row">
      <label for="example-number-input" class="col-1 col-1 offset-1 col-form-label">Avatar</label>
      <div class="col-6">
        <div class="fileform">
          <input type="text" name="avatarName" value="<?= $user->getAvatar()?:'';?>">
          <div class="selectbutton">Upload</div>
          <input id="upload" type="file" name="avatar"
              accept="image/jpeg,image/png,image/gif"

              onchange="uploadFile(this.files[0].name)">
        </div>
      </div>
    </div>
    <div class="form-group row">
      <label for="example-number-input" class="col-1 col-1 offset-1 col-form-label"></label>
      <div class="col-2">
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>
    </div>

  </form>
  </div>
</div>

