<div class="container" id="verify-container">
	<menu id="verify-menu">
		<a href="/payments/verify"><li>Verify Payment Method</li></a>
	    <a class="verify-menu-a" href="/payments/transactions"><li>Transaction History</li></a>
	    <a href="/payments/deposit"><li>Deposit Funds</li></a>
		<a href="/payments/withdraw"><li>Withdraw Money</li></a>
	</menu>
	<div class="row" >
		<div id="verify-title">
		<h1>Transaction History</h1>
		</div>
    </div>
	<ul id="tabs">
		<li><a title="tab1" href="#">All Transactions</a></li>
		<li><a title="tab2" href="#">Invoices</a></li>
		<li><a title="tab3" href="#">Milestones</a></li>
		<li><a title="tab4" href="#">Pending funds</a></li>
	</ul>
	<div id="content">
		<div id="tab1">
			<table class="table">
				<tr>
					<th>Date</th>
					<th>Transaction</th>
					<th>Invoice</th>
					<th>Amount</th>
					<th>Balance</th>
				</tr>
				<tr>
					<td>08 jul 2016 01:45</td>
					<td>Exam fee-Academic Writing-Level1(USD)</td>
					<td>PDF</td>
					<td>USD</td>
					<td>-5.00</td>
				</tr>
				<tr>
					<td>07 jul 2016 22:48</td>
					<td>Exam fee-US English-Level1(USD)</td>
					<td>PDF</td>
					<td>USD</td>
					<td>-5.00</td>
				</tr>
					<tr>
					<td>23 may 2016 09:37</td>
					<td>Membership monthly fee(USD)</td>
					<td>PDF</td>
					<td>USD</td>
					<td>-0.99</td>
				</tr>
				<tr>
					<td>04 may 2016 02:33</td>
					<td>Done milestone payment(USD)</td>
					<td>PDF</td>
					<td>USD</td>
					<td>10.00</td>
				</tr>
				<tr>
					<td>01 may 2016 04:30</td>
					<td>Transfer for project(USD)</td>
					<td>PDF</td>
					<td>USD</td>
					<td>20.00</td>
				</tr>
			</table>
		</div>
		<div id="tab2">
			<table class="table">
				<tr>
					<th>Freelancer</th>
					<th>Project Name</th>
					<th>Invoice Ref</th>
					<th>Invoice Amount</th>
					<th>Unpaid Amount</th>
					<th>Status</th>
					<th>Actions</th>
				</tr>
				<tr>
					<td>Freelancer</td>
					<td>Exam fee-Academic Writing-Level1(USD)</td>
					<td>ref</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>Freelancer</td>
					<td>Exam fee-US English-Level1(USD)</td>
					<td>ref</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>Freelancer</td>
					<td>Membership monthly fee(USD)</td>
					<td>ref</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>Freelancer</td>
					<td>Done milestone payment(USD)</td>
					<td>ref</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>Freelancer</td>
					<td>Transfer for project(USD)</td>
					<td>ref</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
			</table>		
		</div>
		<div id="tab3">
			<table class="table">
				<tr>
					<th>Created Date</th>
					<th>Employer</th>
					<th>Project Name</th>
					<th>Amount</th>
					<th>Description</th>
					<th>Status</th>
					<th>Actions</th>
				</tr>
				<tr>
					<td>04 may 2016 02:33</td>
					<td>Exam fee-Academic Writing-Level1(USD)</td>
					<td>name</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>03 may 2016 01:17</td>
					<td>Exam fee-US English-Level1(USD)</td>
					<td>name</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>02 may 2016 10:53</td>
					<td>Membership monthly fee(USD)</td>
					<td>name</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>01 may 2016 05:33</td>
					<td>Done milestone payment(USD)</td>
					<td>name</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
				<tr>
					<td>01 may 2016 01:38</td>
					<td>Transfer for project(USD)</td>
					<td>name</td>
					<td>USD</td>
					<td>USD</td>
					<td>*</td>
					<td>v</td>
				</tr>
			</table>		
		</div>
		<div id="tab4">
			<table class="table">
				<tr>
					<th>Date</th>
					<th>Transaction</th>
					<th>Reason</th>
					<th>Currency</th>
					<th>Amount</th>
					<th>Expected time of resolution</th>
				</tr>
				<tr>
					<td>08 jul 2016 01:45</td>
					<td>Exam fee-Academic Writing-Level1(USD)</td>
					<td>reason</td>
					<td>USD</td>
					<td>USD</td>
					<td class="tab4-last-col">2 days</td>
				</tr>
				<tr>
					<td>04 jul 2016 11:43</td>
					<td>Exam fee-US English-Level1(USD)</td>
					<td>reason</td>
					<td>USD</td>
					<td>USD</td>
					<td class="tab4-last-col">3 days</td>
				</tr>
				<tr>
					<td>03 jul 2016 10:41</td>
					<td>Membership monthly fee(USD)</td>
					<td>reason</td>
					<td>USD</td>
					<td>USD</td>
					<td class="tab4-last-col">3 days</td>
				</tr>
				<tr>
					<td>02 jul 2016 01:48</td>
					<td>Done milestone payment(USD)</td>
					<td>reason</td>
					<td>USD</td>
					<td>USD</td>
					<td class="tab4-last-col">2 days</td>
				</tr>
				<tr>
					<td>01 jul 2016 02:23</td>
					<td>Transfer for project(USD)</td>
					<td>reason</td>
					<td>USD</td>
					<td>USD</td>
					<td class="tab4-last-col">3 days</td>
				</tr>
			</table>		
		</div>
	</div>
</div>
