<div class="container" id="verify-container">
	<menu id="verify-menu">
		<a href="/payments/verify"><li>Verify Payment Method</li></a>
	    <a href="/payments/transactions"><li>Transaction History</li></a>
	    <a href="/payments/deposit"><li>Deposit Funds</li></a>
		<a class="verify-menu-a" href="/payments/withdraw"><li>Withdraw Money</li></a>
   </menu>
   <div class="row" >
		<div id="verify-title">
		<h1>Withdrawal Request</h1>
		</div>
    </div>
    <table class="table" id="table-withdrawal">
		<tr>
			<th>Method</th>
			<th>Description</th>
			<th>Fee</th>
		</tr>
		<tr>
			<td>Express Withdrawal</td>
			<td>The fastest method to withdraw funds, directly to your local bank account! Available in selected countries only.</td>
			<td>No fee</td>
		</tr>
		<tr>
			<td>PayPal</td>
			<td>Withdraw funds to your PayPal account.</td>
			<td>No fee</td>
		</tr>
		<tr>
			<td>WebMoney</td>
			<td>Withdraw funds to your WebMoney account.</td>
			<td>No fee</td>
		</tr>				
	</table>
	<div class="withdraw-note">
		<p><strong>Note:</strong> Your first withdrawal is delayed for 15 days for security reasons. </p>
		<p>Withdrawals are processed twice a week, as long as the requests are lodged before: 
		<ul>
			<li>5pm on Sundays EDT (New York), which is 7am on Monday AEST (Sydney). Processed on Monday (NY)/ Tuesday (Sydney).</li>
			<li>5pm on Wednesday EDT (New York), which is 7am on Thursday AEST (Sydney). Processed on Thursday (NY)/ Friday (Sydney).</li>
		</ul>
		Additional fees may also be charged by third party gateways such as PayPal, Skrill and Payoneer. 
		</p>	
	</div>
	<div class="withdraw-title2">
		<h4>Pending Withdrawals</h4>
	</div>
	<table class="table">
		<tr>
			<th>Requested at</th>
			<th>Amount</th>
			<th>Details</th>
			<th>Status</th>
			<th>Processing date</th>
		</tr>
		<tr>
			<td>08/10/2016 at 03:29 EDT</td>
			<td>USD$30.40</td>
			<td>PayPal withdrawal to email example@gmail.com</td>
			<td>Pending</td>
			<td>Mon, 11 Apr 2016 - Tue, 12 Apr 2016</td>
		</tr>
		<tr>
			<td>04/09/2016 at 09:47 EDT</td>
			<td>USD$38.56</td>
			<td>PayPal withdrawal to email example@gmail.com</td>
			<td>Pending</td>
			<td>Tue, 12 Apr 2016 - Wed, 13 Apr 2016</td>
		</tr>
		<tr>
			<td>25/08/2016 at 07:22 EDT</td>
			<td>USD$25.70</td>
			<td>PayPal withdrawal to email example@gmail.com</td>
			<td>Pending</td>
			<td>Wed, 13 Apr 2016 - Thu, 14 Apr 2016</td>
		</tr>				
	</table>
</div>
