<footer class="footer">

  <!--First footer section-->
  <!--Site statistics-->

  <div class="footer-section footer-section-bordered">
    <div class="container">
      <div class="row">

        <div class="col-xl-4 col-lg-4">
          <div class="site-stat">
            <div id="footerRegisterUsersCount" class="site-stat-value">46,432,325</div>
          </div>
          <div class="site-stat-name">
            <span>Registered users</span>
          </div>
        </div>

        <div class="col-xl-4 col-lg-4">
          <div class="site-stat">
            <div id="footerRegisterUsersCount" class="site-stat-value">15,339,839</div>
          </div>
          <div class="site-stat-name">
            <span>Total jobs posted</span>
          </div>
        </div>

      </div>
    </div>
  </div>

  <!--Second footer section-->
  <!--Footer site links-->

  <div class="footer-section">
    <div class="container">
      <div class="row">

        <div class="col-xl-2 col-lg-2 footer-site-links">
          <h3 class="footer-links-title">Company info</h3>
          <ul class="footer-links">
            <li><a href="#" class="footer-link">About Us</a></li>
            <li><a href="#" class="footer-link">Team</a></li>
            <li><a href="#" class="footer-link">Investor</a></li>
            <li><a href="#" class="footer-link">Security</a></li>
            <li><a href="#" class="footer-link">Report Bug</a></li>
            <li><a href="#" class="footer-link">Fees & Charges</a></li>
          </ul>
        </div>

        <div class="col-xl-2 col-lg-2 footer-site-links">
          <h3 class="footer-links-title">Resources</h3>
          <ul class="footer-links">
            <li><a href="#" class="footer-link">Help & FAQ</a></li>
            <li><a href="#" class="footer-link">Blog</a></li>
            <li><a href="#" class="footer-link">Answers</a></li>
            <li><a href="#" class="footer-link">Users directory</a></li>
            <li><a href="#" class="footer-link">Projects directory</a></li>
            <li><a href="#" class="footer-link">Sitemap</a></li>
          </ul>
        </div>

        <div class="col-xl-2 col-lg-2 footer-site-links">
          <h3 class="footer-links-title">Get in touch</h3>
          <ul class="footer-links">
            <li><a href="#" class="footer-link">Contact Us</a></li>
            <li><a href="#" class="footer-link">Advertise with Us</a></li>
            <li><a href="#" class="footer-link">Get Support</a></li>
            <li><a href="#" class="footer-link">Merchandise</a></li>
            <li><a href="#" class="footer-link">Community</a></li>
            <li><a href="#" class="footer-link">Affiliate Program</a></li>
          </ul>
        </div>

        <div class="col-xl-2 col-lg-2 footer-site-links">
          <h3 class="footer-links-title">Company info</h3>
          <ul class="footer-links">
            <li><a href="#" class="footer-link">About Us</a></li>
            <li><a href="#" class="footer-link">Team</a></li>
            <li><a href="#" class="footer-link">Investor</a></li>
            <li><a href="#" class="footer-link">Security</a></li>
            <li><a href="#" class="footer-link">Report Bug</a></li>
            <li><a href="#" class="footer-link">Fees & Charges</a></li>
          </ul>
        </div>

        <div class="col-xl-4 col-lg-4 footer-site-links">
          <h3 class="footer-links-title">CourseNetwork</h3>
          <ul class="footer-links">
            <li><a href="#" class="footer-link">Privacy Policy</a></li>
            <li><a href="#" class="footer-link">Terms & Conditions</a></li>
            <li>
            <p class="footer-copyright">CourseNetwork ® is a registered Trademark of Freelancer Technology
              Pty Limited (ACN 142 189 759)
            </p>
            <p class="footer-copyright">
              Copyright © 2017 CourseNetwork Technology Pty Limited (ACN 142 189 759)
            </p>
            </li>

          </ul>
        </div>

      </div>
    </div>
  </div>

</footer>