<html>
<head>
    <title>Course Network</title>
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/assets/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="/assets/css/main-style.css">
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/application.js"></script>
</head>
<body>
    <?php include 'menu/guest.phtml'; ?>
    <div class="container">
        <?= $viewContent; ?>
    </div>
</body>
</html>