<?php  $user = \System\Auth\UserSession::getInstance()->getIdentity();?>
<div class="verticalAdminMenu col-2 no-padding-right">
  <div class="admin-label">
    <span>Course</span>Network
  </div>
  <ul class="clearfix">
    <li><a href="/using/main" <?php echo ($_SERVER['REQUEST_URI'] == '/using/main') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>My profile</a></li>
    <li><a href="/using/setting" <?php echo ($_SERVER['REQUEST_URI'] == '/using/setting') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Setting</a></li>
    <li><a href="/using/portfolio" <?php echo ($_SERVER['REQUEST_URI'] == '/using/portfolio') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Portfolio</a></li>
    <li><a href="/using/workdiary" <?php echo ($_SERVER['REQUEST_URI'] == '/using/workdiary') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Work diary</a></li>
    <li><a href="/using/jobsstatus" <?php echo ($_SERVER['REQUEST_URI'] == '/using/jobsstatus') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Job status</a></li>
    <li><a href="/using/news" <?php echo ($_SERVER['REQUEST_URI'] == '/using/news') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>News</a></li>
    <li><a href="/using/menuinfo" <?php echo ($_SERVER['REQUEST_URI'] == '/using/menuinfo') ? "class='active'" : ""; ?>><i class="fa fa-home" aria-hidden="true"></i>Menu Info</a></li>
    <?php  if ($user !== null) :?>
    <li><a  href="/using/main" class="avatar_foto"><img src="/assets/img/user-page/avatar/<?= $user->getAvatar();?>"  alt="avatar "></a></li>
      <li><a  href="/using/main" id="avatar_foto"><?= $user->getEmail()?></a></li>
    <?php endif; ?>
  </ul>
</div>





