<!--Main page-->
<div id="homePage" class="home-container fullheight">
  <!-- Bootstrap 4 carousel -->
  <section class="section-home section-carousel">
    <div id="homeSlider" class="carousel slide" data-ride="carousel">
      <!--Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#homeSlider" data-slide-to="0" class="active"></li>
        <li data-target="#homeSlider" data-slide-to="1"></li>
        <li data-target="#homeSlider" data-slide-to="2"></li>
        <li data-target="#homeSlider" data-slide-to="3"></li>
        <li data-target="#homeSlider" data-slide-to="4"></li>
      </ol>

      <!--Wrape for sliders-->

      <div class="carousel-inner" role="listbox">

        <div class="carousel-item active">
          <img src="/assets/img/index-page/slides/slide-01.jpeg" class="d-block img-fluid fill" alt="">
          <div class="carousel-caption d-none d-md-block">
            <h3>WORLD CLASS DESIGNS</h3>
            <ul class="caption-list">
              <li>Stunning Logos</li>
              <li>Vectors</li>
              <li>3D Graphics</li>
              <li>Illustrations</li>
              <li>Banners</li>
              <li>Avatars</li>
            </ul>
          </div>
        </div>

        <div class="carousel-item">
          <img src="/assets/img/index-page/slides/slide-09.jpg" class="d-block img-fluid fill" alt="">
          <div class="carousel-caption d-none d-md-block">
            <h3>Custom Websites</h3>
            <ul class="caption-list">
              <li>Drupal</li>
              <li>Wordpress</li>
              <li>PHP</li>
              <li>HTML</li>
              <li>CSS</li>
              <li>Javascript</li>
            </ul>
          </div>
        </div>

        <div class="carousel-item">
          <img src="/assets/img/index-page/slides/slide-04.jpg" class="d-block img-fluid fill" alt="">
          <div class="carousel-caption d-none d-md-block">
            <h3>And Everything In-Between</h3>
            <ul class="caption-list">
              <li>SEO</li>
              <li>Copywriting</li>
              <li>Website Content</li>
              <li>Video</li>
              <li>Mobile Apps</li>
            </ul>
          </div>
        </div>

        <div class="carousel-item">
          <img src="/assets/img/index-page/slides/slide-10.jpg" class="d-block img-fluid fill" alt="">
          <div class="carousel-caption d-none d-md-block">
            <h3>All Done Remotely</h3>
            <p class="caption-text">
              Super fast with Guaranteed Results
            </p>
          </div>
        </div>

        <div class="carousel-item">
          <img src="/assets/img/index-page/slides/slide-11.jpg" class="d-block img-fluid fill" alt="">
          <div class="carousel-caption d-none d-md-block">
            <h3>Work with top-notch talent</h3>
            <p class="caption-text">Our community of 90,000+ curated experts is ready to start today</p>
          </div>
        </div>


      </div>

    </div>

    <!-- Form above the carousel -->
    <div class="get-started-form">
      <div class="container clearfix">
        <div class="col-xl-8 offset-xl-3 clearfix">
          <form action="" id="getstarted" method="post">
            <div class="row">
              <div class="col-xl-7 no-padding-left">
                <input type="text" name="" id="getStartedTitle" placeholder="What type of work do you need?">
              </div>
              <div class="col-xl-2 no-padding-left">
                <input type="submit" class=" btn-custom1 call-to-action" value="Let's go  ">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

  </section>

</div>
<!--end carousel-->

<!-- First inform section -->
<div class="home-container clearfix">
  <section class="section-home section-why-course-network clearfix">
    <div class="container">
      <h3><?= \System\Auth\Session::getInstance()->getIdentity(); ?></h3>
      <div class="row">
        <div class="col-xl-4">
          <img src="/assets/img/index-page/icons/vault16.png" alt="" class="why-course-newtwor-img">
          <h5>Safe work</h5>
          <p>Reserve funds for service
            It will allow you to be confident in a fair
            and the successful outcome of the project.
          </p>
        </div>

        <div class="col-xl-4">
          <img src="/assets/img/index-page/icons/group.png" alt="" class="why-course-newtwor-img">
          <h5>Proven performers </h5>
          <p>Reviews of other customers
            executed projects, audited
            personal data freelancers.
          </p>
        </div>

        <div class="col-xl-4">
          <img src="/assets/img/index-page/icons/tablet.png" alt="" class="why-course-newtwor-img">
          <h5>Powerful platform</h5>
          <p>There is a convenient system
            private messaging, project forum
            investments and other instruments.
          </p>
        </div>

      </div>
    </div>
  </section>
</div>

<!-- Second inform section -->

<div class="home-container clearfix">
  <section class="section-home section-how-it-works section-gray clearfix">
    <div class="container">
      <h3>How it works</h3>
      <div class="row">
        <div class="col-xl-3">
          <img src="/assets/img/index-page/icons/megaphone.png" alt="" class="why-course-newtwor-img">
          <h5>FIND</h5>
          <p>Post a job to tell us about your project.
            We'll quickly match you with the right freelancers.
          </p>
        </div>

        <div class="col-xl-3">
          <img src="/assets/img/index-page/icons/check.png" alt="" class="why-course-newtwor-img">
          <h5>HIRE</h5>
          <p>Browse profiles, reviews, and proposals then
            interview top candidates. Hire a favorite and begin your project.
          </p>
        </div>

        <div class="col-xl-3">
          <img src="/assets/img/index-page/icons/browser.png" alt="" class="why-course-newtwor-img">
          <h5>WORK</h5>
          <p>Use the CourseNetwork platform to chat, share files,
            and collaborate from your desktop or on the go.
          </p>
        </div>

        <div class="col-xl-3">
          <img src="/assets/img/index-page/icons/money.png" alt="" class="why-course-newtwor-img">
          <h5>PAY</h5>
          <p>Invoicing and payments happen through CourseNetwok. With CourseNetwork Protection
            , only pay for work you authorize.
          </p>
        </div>

      </div>
    </div>
  </section>
</div>

<!-- Animated categories -->

<div class="home-container clearfix">
  <div class="section-home section-categories">
    <div class="container">
      <h3>Categories</h3>
      <div class="row">

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-design.jpg" alt="img01"/>
              <figcaption>
                <h4>Design</h4>
                <p>
                  Graphic Designers<br>
                  UX/UI Designers<br>
                  Photo editors<br>
                  <span>and more...</span>
                </p>

              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-web-dev.jpg" alt="img01"/>
              <figcaption>
                <h4>Web development</h4>
                <p>
                  Front-end developers<br>
                  Back-end developers<br>
                  Drupal fullstack <br>
                  <span>and more...</span>
                </p>
              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-writing.jpg" alt="img01"/>
              <figcaption>
                <h4>Writing & translation</h4>
                <p>
                  Blog writers<br>
                  Content writers<br>
                  Copywriters<br>
                  <span>and more...</span>
                </p>              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-marketing.jpg" alt="img01"/>
              <figcaption>
                <h4>Sales & marketing</h4>
                <p>
                  Seo specialists<br>
                  Email automators<br>
                  Marketing experts<br>
                  <span>and more...</span>
                </p>              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-accounting.jpg" alt="img01"/>
              <figcaption>
                <h4>Accountants & consultants</h4>
                <p>
                  Tax consultants<br>
                  Bookkeepers<br>
                  Financial modelers<br>
                  <span>and more...</span>
                </p>              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-assistant.jpg" alt="img01"/>
              <figcaption>
                <h4>Virtual assistans</h4>
                <p>
                  Personal assistants<br>
                  Transcriptionists<br>
                  Web researches<br>
                  <span>and more...</span>
                </p>              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-support.jpg" alt="img01"/>
              <figcaption>
                <h4>Support</h4>
                <p>
                  Phone support<br>
                  Email support<br>
                  live chat support<br>
                  <span>and more...</span>
                </p>              </figcaption>
            </figure>
          </a>
        </div>

        <div class="col-xl-3 home-categories-item">
          <a href="#">
            <figure class="effect-sadie">
              <img src="/assets/img/index-page/animated-categories/thumb-mobile-dev.jpg" alt="img01"/>
              <figcaption>
                <h4>Sofware dev & mobile</h4>
                <p>
                  IOS app developer<br>
                  UX/UI Designer<br>
                  Android developer<br>
                  <span>and more...</span>
                </p>              </figcaption>
            </figure>
          </a>
        </div>


      </div>
    </div>
  </div>
</div>

<!-- Browse the top freelancers... -->

<div class="home-container clearfix">
  <section class="section-home section-gray section-sponsors clearfix">
    <div class="container">
      <h3>Our sponsors</h3>
      <div class="row">
        <div class="col-xl-3">
          <img src="/assets/img/index-page/sponsors/sponsor-1.png" alt="">
        </div>
        <div class="col-xl-3">
          <img src="/assets/img/index-page/sponsors/sponsor-2.png" alt="">
        </div>
        <div class="col-xl-3">
          <img src="/assets/img/index-page/sponsors/sponsor-3.png" alt="">
        </div>
        <div class="col-xl-3">
          <img src="/assets/img/index-page/sponsors/sponsor-4.png" alt="">
        </div>
      </div>
    </div>
  </section>
</div>

<div class="home-container clearfix">
  <section class="section-home section-top clearfix">
    <div class="container">
      <h3>Browse the top freelancers in each category</h3>
      <ul class="col-xl-12 top-category-list">
        <li><a href="#">Android developers</a></li>
        <li><a href="#">AngularJS Developers</a></li>
        <li><a href="#">Bookkeepers</a></li>
        <li><a href="#">C# Developers</a></li>
        <li><a href="#">Content Writers</a></li>
        <li><a href="#">Copywriters</a></li>
        <li><a href="#">Customer Service Representatives</a></li>
        <li><a href="#">Data Entry Specialists</a></li>
        <li><a href="#">Data Entry Specialists</a></li>
        <li><a href="#">Excel Experts</a></li>
        <li><a href="#">Facebook Marketers</a></li>
        <li><a href="#">Graphic Designers</a></li>
        <li><a href="#">iOS Developers</a></li>
        <li><a href="#">JavaScript Developers</a></li>
        <li><a href="#">jQuery Developers</a></li>
        <li><a href="#">Mobile App Developers</a></li>
        <li><a href="#">Objective-C Developers</a></li>
        <li><a href="#">PHP Developers</a></li>
        <li><a href="#">Python Developers</a></li>
        <li><a href="#">Sales Consultants</a></li>
        <li><a href="#">SEO Experts</a></li>
        <li><a href="#">Social Media Consultants</a></li>
        <li><a href="#">Swift Developers</a></li>
        <li><a href="#">Technical Writers</a></li>
        <li><a href="#">UI Designers</a></li>
        <li><a href="#">UX Designers</a></li>
        <li><a href="#">Virtual Assistants</a></li>
        <li><a href="#">Web Designers</a></li>
        <li><a href="#">Wordpress Developers</a></li>
        <li><a href="#">Writers</a></li>
        <li><a href="#">See all categories</a></li>
      </ul>
    </div>
  </section>
</div>